<?php

function kifiform_theme() {
  return [
    'kifiform_captcha' => [
      'template' => 'captcha',
      'render element' => 'element',
    ],
    'kifiform_rating' => [
      'variables' => [
        'rating' => 0,
        'votes' => 0,
        'allow_voting' => FALSE,
        'display_votes' => FALSE,
        'form_url' => '',
        'id' => null,
      ]
    ],
    'kifiform_rating_thumbs' => [
      'variables' => [
        'form_url' => null,
      ]
    ],
  ];
}


function kifiform_field_widget_info_alter(array &$info) {
  $info['number']['field_types'][] = 'kifiform_view_counter';
}
